### PR TITLE
.NET Standard Runtime

### PR DESCRIPTION
**Pull request by lostinplace**
Note:  one of the tcp interop tests fails, but it was failing before my changes (the test doesn't make sense currently)

### CODE REVIEW

**Comment by c80k** [comment]
Thanks for providing the PR! I added my review comments. One major point: The .NET Core 2.1 support for Spans brings major performance benefits. Just omitting them in favor of legacy feels like a step in the wrong direction. I suggest conditional compilation, even though it looks ugly. But this way .NET Core 2.1-enabled users may take advantage from the new&faster APIs.

**Comment by merarischroeder** [comment]
More focus should be on completeness for most users first. The performance should wait.

There probably is a performance benefit, but it would be slight and likely unnoticed by users. A benchmark of 1 million messages might show 20% performance improvement (for example), but the difference for an individual message for a single user is only about latency (not throughput). The difference between 1.2ns and 1ns is negligible when there is network jitter of several ms.

Some developers might have throughput needs, but they would be the minority, and most likely in a position where they can scale up hardware for now.

**Comment by c80k** [comment]
I just created branch [net-standard-runtime-mixed](https://github.com/c80k/capnproto-dotnetcore/tree/net-standard-runtime-mixed). It is a dual solution which combines both the Std 2.0 backport + 2.1, using conditional compilation. This should be a viable compromise.

**Comment by lostinplace** [comment]
do we have any metrics on what the performance benefit is here?

**Comment by lostinplace** [comment]
Also, it seems like this solution doesn't really resolve the issue, any user that wants to use this library will have to rebuild on the appropriate platform,, either that or there would have to be multiple releases

**Comment by lostinplace** [comment]
additionally, it looks like your branch strips out overrun detection/prevention

**Comment by lostinplace** [comment]
also, to be clear, I've spoekn to several people who are still using the .NET framework and would like to use it, I'm not sure that .net standard 2. is "legacy" yet

That said, it looks like when 2.1 drops, this will be a non-issue

**Comment by lostinplace** [comment]
I've gone over your branch, and I think it could use some work.  If you've got feedback I'll happily integrate it into this PR,  it seems like your main concerns are:

* You want to understand how this will impact performance
* you think that users should have the ability to regulate performance through custom builds
* you want to make sure that we're not compromising code quality to support users on outdated platforms

Does that seem right?

**Comment by c80k** [comment]
Hi Chris, excellent summary! Some more explanations:
- Performance: While I acknowledge that performance might not be that relevant to many users, it is important to me. I've been evaluating a use case where capnp is used for inter-process communication on localhost (no "actual" networking involved). In such scenarios, framework overhead does matter. I don't have performance measurements yet, but my initial implementation already considers that aspect. It seems obvious that the 2.0 backport must be "somewhat" slower due to its additional array allocations and its hand-crafted conversion loop. But I cannot quantify the actual slowdown without serious measurement. Nevertheless, I don't see any reason why not to release a 2.1-based implementation, too.
- I acknowledge that compatibility and completeness are crucial aspects for many users. It's awesome that you provided that backport, and we should combine our forces. Describing 2.0 as "legacy" was a rhethorical exaggeration from my side. Even after release of .NET Standard 2.1, supporting 2.0 will probably remain relevant for several years, since users might be stuck for some reasons (configuration management, other tools/frameworks, commercial aspects, your supervisor, pick any). But I also think that it's worth integrating cutting-edge features from newest available .NET Core and maybe other frameworks. Because it's fun, because I can, and because this is open source (...and probably people should consider paying for the "less fun" aspects for software development ;-) ). This leads me to proposed approach: One release produces multiple deployments. So far, we can build a .NET Standard 2.0 and a .NET Core 2.1 assembly from the same code base. Thus, I wouldn't call it "custom build", since both assemblies can be officially released and published.
- Agree, code quality must not be compromised. Considering your concrete PR, this aspect is actually a non-issue. I made very few review comments on possibly introduced bugs, but all of them are easily solvable. I don't see any principal quality issue with the backport itself.

**Comment by merarischroeder** [comment]
Very true. 

The inter-process communication use-case is certainly more sensitive to performance. In particular, Spans improve performance in two ways (from what I remember):

1. Less memory copying (using the same buffer but changing the focus point)
2. Less GC (reusing byte[] and objects)

**Polyfill?**

What if [1] and [2] can be achieved with custom classes in earlier .Net Standard versions, and with built-in features in later .Net Standard versions. 

That would be better than having conditional code, and then even the earlier version will have improved performance.

**Comment by c80k** [comment]
I‘m not sure whether it is possible to provide such a polyfill without relying on conditional compilation.

Moreover, it would probably require /unsafe code, which might be prohibitive for many users (or at least scare them off).

**Comment by merarischroeder** [comment]
The necessary API entry points remain the same. In the older .Net Standard version it's polyfill code files. These files would be conditionally included in the project (so yes, it would be conditional compilation).

The implementation doesn't need any unsafe code. 

[1] the idea of a Span is also simple. 

[2] An ArrayPool which is a very simple concept (Newtownsoft's JSON Serialiser has used ArrayPools for a while (before SPAN came along)).

Most of the code is just plumbing. There might be some additional "unsafe" performance tweaks in .Net Standard version, but I believe most of the performance benefits can be accomplished with safe code.

I think my idea of a polyfill is dependent on the availability of a strong polyfill candidate. It could be custom-built for this project, but surely there's already one out there.

**Comment by c80k** [comment]
@merarischroeder sounds good. Feel free to point out a suitable candidate. Until we found one I suggest to go on with the "dual solution", since it works.

@lostinplace would you provide some details about your concerns?

1. "Does't really solve the problem": As said, we can release & publish two runtime assemblies out of the same code base, one for 2.0 and the other for 2.1. Did I miss something?
2. "Strips out overrun detection/prevention"

**Pull request merged**
